GET http://localhost/api/users/{uuid}
Content-Type: application/json
// Пример Bearer авторизации:
// Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjgwMzY3ODIsImV4cCI6MTcyODA0MDM4Miwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6InRlc3RAdGVzdC50ZXN0MiJ9.BS7JC5C4x287ZfQY92YEa9-B3BhnRBPozrnXl9sFOyK9smWK8elML5sy-ZO55bL6usFznxy4mypGp3zTME0Za30lPZbTZquak7z_LCJqFyF8PWtErT2OS4oeKKLmfykfJ5AsIQwNNXEag9r_5efeYI3W5BDk38FfIjefT6aa7efdunSCNVA3Auh0Vfd7aYjk5MeBDKzYQYlOJ-1bw1at7IojqsBG2m9QEkvjumVWBoI-LH1xDYets9QKymzgY1tIQD4bG4mWmGmEAtIirnKQU6RPhMlEjaTujSLiu7jCYQHgRy6ypD_yGjqhkAC8BWvSMqbstufgb2GF7OoWSzI9Ng
